# Generated by Django 3.1.4 on 2020-12-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges_Info',
            fields=[
                ('college_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('work_email', models.EmailField(max_length=254, verbose_name='work_email')),
                ('job_title', models.CharField(max_length=255)),
                ('college_name', models.CharField(max_length=255)),
            ],
        ),
    ]
